---
- hosts: localhost
  tasks:
    - name: example ec2 group
      ec2_group:
        name: dbsg
        description: an example EC2 group
        vpc_id: vpc-eb3ade90
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0
      register: dbsg
    - debug:
        var: dbsg
    - rds_subnet_group:
        state: present
        region: us-east-1
        name: dbsubnet
        description: My Fancy Ex Parrot Subnet Group
        subnets:
          - subnet-da5f2df5
          - subnet-ee043fa5
      register: dbsubnet
    - debug:
        var: dbsubnet
    - rds:
        command: create
        region: us-east-1
        instance_name: myapp-database
        db_name:userdb
        db_engine: MySQL
        size: 10
        instance_type: db.m1.small
        username: mysql_admin
        password: 1nsecure
        subnet: dbsubnet
        license_model: "general-public-license"
        vpc_security_groups: "{{ dbsg.group_id }}"
        multi_zone: no
        wait: yes
        wait_timeout: 900
      register: mydb
    - debug:
        var: mydb
    - replace:
        path: ./threetier.yaml
        regexp: 'DATABASENAME'
        replace: "{{ mydb.instance.endpoint }}"
        backup: yes
